# Modelos de previsão da potabilidade da água

prever a potabilidade da água

https://www.kaggle.com/datasets/uom190346a/water-quality-and-potability

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
base = pd.read_csv('potabilidade_agua.csv')
base.head(3)

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0

In [3]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB


In [4]:
base.describe()

ph     Hardness        Solids  Chloramines      Sulfate  \
count  2785.000000  3276.000000   3276.000000  3276.000000  2495.000000   
mean      7.080795   196.369496  22014.092526     7.122277   333.775777   
std       1.594320    32.879761   8768.570828     1.583085    41.416840   
min       0.000000    47.432000    320.942611     0.352000   129.000000   
25%       6.093092   176.850538  15666.690297     6.127421   307.699498   
50%       7.036752   196.967627  20927.833607     7.130299   333.073546   
75%       8.062066   216.667456  27332.762127     8.114887   359.950170   
max      14.000000   323.124000  61227.196008    13.127000   481.030642   

       Conductivity  Organic_carbon  Trihalomethanes    Turbidity   Potability  
count   3276.000000     3276.000000      3114.000000  3276.000000  3276.000000  
mean     426.205111       14.284970        66.396293     3.966786     0.390110  
std       80.824064        3.308162        16.175008     0.780382     0.487849  
min      181.483754        2.200000         0.738000     1.450000     0.000000  
25%      365.734414       12.065801        55.844536     3.439711     0.000000  
50%      421.884968       14.218338        66.622485     3.955028     0.000000  
75%      481.792304       16.557652        77.337473     4.500320     1.000000  
max      753.342620       28.300000       124.000000     6.739000     1.000000

In [9]:
base.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [10]:
base['ph'].median()

7.036752103833548

In [13]:
base.fillna(-1, inplace=True)

In [14]:
base.isnull().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [15]:
# funçoes de treino dos dados
def arvore_decisao(tabela, max_depth=None, criterion='gini', splitter='best'):
    X = tabela.drop('Potability', axis=1)
    y = tabela['Potability']
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
    
    cla = DecisionTreeClassifier(max_depth=max_depth, criterion=criterion, splitter=splitter, random_state=42).fit(X_train,y_train)
    
    prev_test = cla.predict(X_test)
    prev_train = cla.predict(X_train)
    
    print('='*60)
    print(accuracy_score(y_test, prev_test))
    print(confusion_matrix(y_test, prev_test))
    print('='*60)
    print(accuracy_score(y_train, prev_train))
    print(confusion_matrix(y_train, prev_train))
    print('='*60)
    
def floresta_aleatoria(tabela, max_depth=None, criterion='gini', n_estimators=100):
    X = tabela.drop('Potability', axis=1)
    y = tabela['Potability']
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
    
    cla = RandomForestClassifier(max_depth=max_depth, criterion=criterion, n_estimators=n_estimators, random_state=42).fit(X_train,y_train)
    
    prev_test = cla.predict(X_test)
    prev_train = cla.predict(X_train)
    
    print('='*60)
    print(accuracy_score(y_test, prev_test))
    print(confusion_matrix(y_test, prev_test))
    print('='*60)
    print(accuracy_score(y_train, prev_train))
    print(confusion_matrix(y_train, prev_train))
    print('='*60)
    
def knn(tabela, n_neighbors=5, weights='uniform', algorithm='auto', p=2):
    X = tabela.drop('Potability', axis=1)
    y = tabela['Potability']
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
    
    cla = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights, algorithm=algorithm, p=p).fit(X_train,y_train)
    
    prev_test = cla.predict(X_test)
    prev_train = cla.predict(X_train)
    
    print('='*60)
    print(accuracy_score(y_test, prev_test))
    print(confusion_matrix(y_test, prev_test))
    print('='*60)
    print(accuracy_score(y_train, prev_train))
    print(confusion_matrix(y_train, prev_train))
    print('='*60)

In [32]:
arvore_decisao(base, max_depth=9, criterion='entropy')

0.6398046398046398
[[445  65]
 [230  79]]
0.7431827431827431
[[1434   54]
 [ 577  392]]


In [133]:
floresta_aleatoria(base, max_depth=8)

0.6837606837606838
[[486  24]
 [235  74]]
0.7806267806267806
[[1486    2]
 [ 537  432]]


In [81]:
knn(base, n_neighbors=6, p=1)

0.5860805860805861
[[432  78]
 [261  48]]
0.6853886853886854
[[1360  128]
 [ 645  324]]


In [82]:
from sklearn.preprocessing import StandardScaler

In [86]:
colunas = base.columns

In [93]:
base2 = pd.DataFrame(StandardScaler().fit_transform(base), columns=colunas).drop('Potability', axis=1)

In [94]:
base2['Potability'] = base.Potability

In [112]:
arvore_decisao(base2, max_depth=6)

0.6446886446886447
[[457  53]
 [238  71]]
0.6862026862026862
[[1398   90]
 [ 681  288]]


In [146]:
floresta_aleatoria(base2, max_depth=8)

0.6837606837606838
[[486  24]
 [235  74]]
0.7806267806267806
[[1486    2]
 [ 537  432]]


In [171]:
knn(base2, n_neighbors=16, p=1)

0.6410256410256411
[[465  45]
 [249  60]]
0.6597476597476597
[[1403   85]
 [ 751  218]]


In [172]:
base = pd.read_csv('potabilidade_agua.csv')

In [173]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB


In [179]:
coluna = base.columns[base.isnull().sum()/base.shape[0] > 0.1]

In [182]:
base.drop(coluna, axis=1, inplace=True)

In [183]:
base['Trihalomethanes'].mean()

66.39629294676803

In [185]:
base['Trihalomethanes'].fillna(base['Trihalomethanes'].mean(), inplace=True)

In [186]:
base.isnull().sum()

Hardness           0
Solids             0
Chloramines        0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [206]:
arvore_decisao(base, max_depth=5, criterion='entropy', splitter='random')

0.6227106227106227
[[498  12]
 [297  12]]
0.6227106227106227
[[1476   12]
 [ 915   54]]


In [223]:
floresta_aleatoria(base, max_depth=4)

0.6202686202686203
[[501   9]
 [302   7]]
0.6255596255596255
[[1486    2]
 [ 918   51]]


In [239]:
knn(base, n_neighbors=13, p=1)

0.5824175824175825
[[404 106]
 [236  73]]
0.6528286528286529
[[1271  217]
 [ 636  333]]


In [240]:
base = pd.read_csv('potabilidade_agua.csv')
base.head(3)

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0

In [242]:
base['ph'].fillna(base['ph'].mean(), inplace=True)

In [243]:
base['Sulfate'].fillna(base['Sulfate'].mean(), inplace=True)

In [244]:
base['Trihalomethanes'].fillna(base['Trihalomethanes'].mean(), inplace=True)

In [245]:
base.isnull().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [267]:
arvore_decisao(base, max_depth=12)

0.652014652014652
[[422  88]
 [197 112]]
0.7871387871387872
[[1425   63]
 [ 460  509]]


In [305]:
floresta_aleatoria(base, max_depth=9, n_estimators=210)

0.6825396825396826
[[484  26]
 [234  75]]
0.796092796092796
[[1488    0]
 [ 501  468]]


In [327]:
knn(base, n_neighbors=14)

0.6043956043956044
[[457  53]
 [271  38]]
0.643060643060643
[[1373  115]
 [ 762  207]]
